language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7

sudo: false

install:
- pip install tox-travis

script:
- tox

# Coverage data generation
- pip install "Django<2.2" flake8 coverage codecov
- flake8 --config flake8.cfg .
- coverage run setup.py test
- coverage report

after_success:
- codecov